=== pvf70/OsBiToolsWs/OsBiWsWpShared/src/main/resources/xsd/wp.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<xsd:element name="wp" type="WebPage" />

	<xsd:complexType name="WebPage">
		<xsd:sequence>
			<xsd:element name="panels" type="ComponentPanels"
				minOccurs="1" maxOccurs="1" />
		</xsd:sequence>

		<xsd:attribute name="descr" use="optional" type="xsd:string" />
		<xsd:attribute name="copyright" use="optional" type="xsd:string" />
		<xsd:attribute name="title" use="optional" type="xsd:string" />
		<xsd:attribute name="charset" use="optional" type="xsd:string" />
		<xsd:attribute name="page_loading" use="optional" type="xsd:string" />
		<xsd:attribute name="ver_max" use="required" type="xsd:int" />
		<xsd:attribute name="ver_min" use="required" type="xsd:int" />
		<xsd:attribute name="inc" use="required" type="xsd:int" />
	</xsd:complexType>

	<xsd:complexType name="ComponentPanels">
		<xsd:sequence>
			<xsd:element name="panel" type="ComponentPanel"
				minOccurs="1" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="ComponentPanel">
		<xsd:sequence>
			<xsd:choice minOccurs="1" maxOccurs="unbounded">
				<xsd:element name="wwg_cont" type="WebWidgetContainer" />
				<xsd:element name="wwg_chart" type="WebWidgetChart" />
				<xsd:element name="wwg_ctrl" type="WebWidgetControl" />
			</xsd:choice>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="WebWidget">
		<xsd:sequence>
			<xsd:element name="props" type="WebWidgetProperties"
				minOccurs="1" maxOccurs="1" />
			<xsd:element name="prop_groups" type="WebWidgetPropertiesGroups"
				minOccurs="0" maxOccurs="1" />
		</xsd:sequence>

		<xsd:attribute name="uid" type="xsd:int" use="required">
			<xsd:annotation>
				<xsd:documentation>
					WebWidget unique id on Web Page
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>

		<xsd:attribute name="idx" type="xsd:int" use="required">
			<xsd:annotation>
				<xsd:documentation>
					WebWidget index among other widget on the same
					level inside container
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>

		<xsd:attribute name="class_name" type="xsd:string" use="required">
			<xsd:annotation>
				<xsd:documentation>
					WebWidget class name
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
	</xsd:complexType>

	<xsd:complexType name="WebWidgetProperties">
		<xsd:sequence>
			<xsd:element name="prop" type="WebWidgetProperty"
				minOccurs="1" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="WebWidgetProperty">
		<xsd:attribute name="name" type="xsd:string" use="required">
			<xsd:annotation>
				<xsd:documentation>
					Property Name
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>

		<xsd:attribute name="value" type="xsd:string" use="required">
			<xsd:annotation>
				<xsd:documentation>
					Property Value
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
	</xsd:complexType>

	<xsd:complexType name="WebWidgetContainer">
		<xsd:complexContent>
			<xsd:extension base="WebWidget">
				<xsd:sequence>
					<xsd:element name="wwg_list" type="ComponentPanel"
						minOccurs="0" maxOccurs="1" />
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="WebWidgetChart">
		<xsd:complexContent>
			<xsd:extension base="WebWidget">
				<xsd:attribute name="engine" type="xsd:string">
					<xsd:annotation>
						<xsd:documentation>
							Charting library engine, for ex. "jqplot"
						</xsd:documentation>
					</xsd:annotation>
				</xsd:attribute>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="WebWidgetPropertiesGroups">
		<xsd:sequence>
			<xsd:element name="prop_group" type="WebWidgetPropertiesGroup"
				minOccurs="1" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="WebWidgetPropertiesGroup">
		<xsd:sequence>
			<xsd:element name="props" type="WebWidgetProperties"
				minOccurs="1" maxOccurs="unbounded" />
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string" use="required">
			<xsd:annotation>
				<xsd:documentation>
					Name of group of properties
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
	</xsd:complexType>

	<xsd:complexType name="WebWidgetControl">
		<xsd:complexContent>
			<xsd:extension base="WebWidget" />
		</xsd:complexContent>
	</xsd:complexType>
</xsd:schema>

=== pvf70/OsBiToolsWs/OsBiWsWpShared/src/test/resources/com/osbitools/ws/shared/demo/config/sites/wp_containers.xml
<?xml version="1.0" encoding="UTF-8"?>
<wp xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
      xsi:noNamespaceSchemaLocation="http://www.osbitools.com/xsd/wp.xsd" 
      ver_max="1" ver_min="0" inc="1">
	<panels>
		<panel>
			<wwg_cont uid="1" idx="0" class_name="com.osbitools.containers.tab_box">
				<props>
					<prop name="id" value="com_osbitools_containers_tab_box_1"/>
				</props>
				<wwg_list>
					<wwg_cont uid="2" idx="0" class_name="com.osbitools.containers.tab_box">
						<props>
							<prop name="id" value="com_osbitools_containers_tab_box_2"/>
						</props>
						<wwg_list>
							<wwg_cont uid="5" idx="0" class_name="com.osbitools.containers.header_box">
								<props>
									<prop name="id" value="com_osbitools_containers_header_box_5"/>
								</props>
							</wwg_cont>
						</wwg_list>
					</wwg_cont>
				</wwg_list>
			</wwg_cont>
			<wwg_cont uid="3" idx="1" class_name="com.osbitools.containers.header_box">
				<props>
					<prop name="id" value="com_osbitools_containers_header_box_3"/>
				</props>
				<wwg_list>
					<wwg_cont uid="4" idx="0" class_name="com.osbitools.containers.tab_box">
						<props>
							<prop name="id" value="com_osbitools_containers_tab_box_4"/>
						</props>
					</wwg_cont>
				</wwg_list>
			</wwg_cont>
		</panel>
	</panels>
</wp>

=== pvf70/OsBiToolsWs/OsBiWsWpShared/src/test/resources/com/osbitools/ws/shared/demo/config/sites/test/bar_chart.xml
<?xml version="1.0" encoding="UTF-8"?>
<wp xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:noNamespaceSchemaLocation="http://www.osbitools.com/xsd/wp.xsd" 
		ver_max="1" ver_min="0" descr="" inc="8">
	<panels>
		<panel>
			<wwg_chart uid="3" idx="0" class_name="com.osbitools.charts.jqplot.bar">
				<props>
						<prop name="id" value="com_osbitools_charts_bar_3" />
						<prop name="size_width" value="300" />
						<prop name="size_height" value="300" />
						<prop name="db_conn" value="hsql" />
						<prop name="ds" value="tt.static" />
						<prop name="is_animate" value="true" />
						<prop name="x_axis" value="NAME" />
				</props>
				<prop_groups>
					<prop_group name="series">
						<props>
								<prop name="label" value="LL_ID" />
								<prop name="y_axis" value="ID" />
						</props>
						<props>
								<prop name="label" value="LL_TEST" />
								<prop name="y_axis" value="TEST" />
						</props>
					</prop_group>
				</prop_groups>
			</wwg_chart>
		</panel>
	</panels>
</wp>
