=== pvf70/OsBiToolsWs/OsBiWsDsShared/src/main/resources/xsd/ds.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<xsd:element name="ds" type="DataSetDescr" />

	<xsd:complexType name="DataSetDescr">
		<xsd:complexContent>
			<xsd:extension base="DataSetExt">
				<xsd:sequence>
					<xsd:element name="req_params" type="RequestParameters"
						minOccurs="0" maxOccurs="1" />
					<xsd:choice minOccurs="1" maxOccurs="1">
						<xsd:element name="group_data" type="GroupData" />
						<xsd:element name="static_data" type="StaticData" />
						<xsd:element name="csv_data" type="CsvData"/>
						<xsd:element name="sql_data" type="SqlData" />
						<xsd:element name="xml_data" type="XmlData" />
					</xsd:choice>
				</xsd:sequence>

				<xsd:attribute name="descr" use="optional" type="xsd:string" />
				<xsd:attribute name="enabled" type="xsd:boolean"
					default="true" />
				<xsd:attribute name="ver_max" use="required" type="xsd:int" />
				<xsd:attribute name="ver_min" use="required" type="xsd:int" />
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="DataSetExt">
		<xsd:sequence>
			<xsd:element name="lang_map" type="LangMap" minOccurs="0"
				maxOccurs="1" />

			<xsd:element name="ex_columns" type="ExColumns"
				minOccurs="0" maxOccurs="1" />

			<xsd:element name="sort_by_grp" type="SortGroup"
				minOccurs="0" maxOccurs="1" />

			<xsd:element name="filter" type="ConditionFilter"
				minOccurs="0" maxOccurs="1" />
		</xsd:sequence>
		<xsd:attribute name="idx" type="xsd:int" use="optional">
			<xsd:annotation>
				<xsd:documentation>
					Used by DsGroup to populate DataSet index inside of group
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
	</xsd:complexType>

	<xsd:complexType name="RequestParameters">
		<xsd:sequence>
			<xsd:element name="param" type="RequestParameter"
				minOccurs="1" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="RequestParameter">
		<xsd:attribute name="name" type="xsd:ID" use="required" />
		<xsd:attribute name="java_type" type="xsd:string" use="required" />
		<xsd:attribute name="size" type="xsd:int" use="optional">
			<xsd:annotation>
				<xsd:documentation>
					Optional component for String types
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="is_mandatory" type="xsd:boolean" default="false">
      <xsd:annotation>
        <xsd:documentation>
          Optional flag to mark request parameter as mandatory.
          Default: false
        </xsd:documentation>
      </xsd:annotation>
    </xsd:attribute>
	</xsd:complexType>

	<!-- DataSetSpec -->

	<xsd:complexType name="DataSetSpec">
		<xsd:sequence>
			<xsd:element name="columns" type="Columns" minOccurs="0"
				maxOccurs="1">
				<xsd:annotation>
					<xsd:documentation>Java type for non-string columns
						that needs to be included into calculation
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Columns">
		<xsd:sequence>
			<xsd:element name="column" type="ColumnHeader" minOccurs="1"
				maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="ColumnHeader">
		<xsd:complexContent>
			<xsd:extension base="Cell">
				<xsd:attribute name="java_type" type="xsd:string" use="required" />
				<xsd:attribute name="on_error" type="xsd:string" use="required" />
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="GroupDataSetDescr">
		<xsd:complexContent>
			<xsd:extension base="DataSetExt">
				<xsd:sequence>
					<xsd:element name="group_data" type="GroupData"
						minOccurs="1" maxOccurs="1" />
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="GroupData">
		<xsd:complexContent>
			<xsd:extension base="DataSetSpec">
				<xsd:sequence>
				  <xsd:element name="ds_list" minOccurs="1" maxOccurs="1"
            type="DataSetExtList" />
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

  <xsd:complexType name="DataSetExtList">
	  <xsd:sequence>
	    <xsd:choice minOccurs="1" maxOccurs="unbounded">
	      <xsd:element name="group_ds" type="GroupDataSetDescr" />
	      <xsd:element name="static_ds" type="StaticDataSetDescr" />
	      <xsd:element name="csv_ds" type="CsvDataSetDescr" />
	      <xsd:element name="sql_ds" type="SqlDataSetDescr" />
	      <xsd:element name="xml_ds" type="XmlDataSetDescr" />
	    </xsd:choice>
	  </xsd:sequence>
  </xsd:complexType>
  
	<xsd:complexType name="Cell">
		<xsd:attribute name="name" type="xsd:string" use="required" />
	</xsd:complexType>

	<xsd:complexType name="RowCell">
		<xsd:complexContent>
			<xsd:extension base="Cell">
				<xsd:attribute name="value" type="xsd:string" use="required" />
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="LangMap">
		<xsd:sequence>
			<xsd:element name="column" type="LangColumn" minOccurs="0"
				maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="LangColumn">
		<xsd:complexContent>
			<xsd:extension base="Cell" />
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="OrderedList">
		<xsd:attribute name="idx" type="xsd:int" use="required" />
	</xsd:complexType>

	<xsd:complexType name="ConditionFilter">
		<xsd:simpleContent>
			<xsd:extension base="xsd:string" />
		</xsd:simpleContent>
	</xsd:complexType>

	<xsd:complexType name="SortGroup">
		<xsd:sequence>
			<xsd:element name="sort_by" type="SortCond" minOccurs="1"
				maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:simpleType name="SortTypes">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="asc" />
			<xsd:enumeration value="desc" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="StringSort">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="natural" />
			<xsd:enumeration value="collator" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:complexType name="SortCond">
		<xsd:complexContent>
			<xsd:extension base="OrderedList">
				<xsd:attribute name="column" type="xsd:string" use="required" />
				<xsd:attribute name="sequence" type="SortTypes" use="optional"
					default="asc" />
				<xsd:attribute name="unique" type="xsd:boolean" use="optional"
					default="false" />
				<xsd:attribute name="str_sort" type="StringSort" use="optional"
					default="natural" />
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="ExColumns">
		<xsd:sequence>
			<xsd:element name="auto_inc" type="AutoIncColumns"
				minOccurs="0" />
			<xsd:element name="calc" type="CalcColumns" minOccurs="0" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="AutoIncColumns">
		<xsd:sequence>
			<xsd:element name="column" type="AutoIncColumn"
				minOccurs="1" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="AutoIncColumn">
		<xsd:complexContent>
			<xsd:extension base="Cell">
				<xsd:attribute name="start_from" type="xsd:int" use="optional"
					default="0" />
				<xsd:attribute name="inc_by" type="xsd:int" use="optional"
					default="1" />
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="CalcColumns">
		<xsd:sequence>
			<xsd:element name="column" type="CalcColumn" minOccurs="1"
				maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="CalcColumn">
		<xsd:simpleContent>
			<xsd:extension base="xsd:string">
				<xsd:attribute name="name" type="xsd:string" use="required" />
				<xsd:attribute name="java_type" type="xsd:string" use="required" />
				<xsd:attribute name="stop_on_error" type="xsd:boolean"
					default="true" />
				<xsd:attribute name="error_value" type="xsd:string" />
			</xsd:extension>
		</xsd:simpleContent>
	</xsd:complexType>

	<!-- Static DataSet -->

	<xsd:complexType name="StaticDataSetDescr">
		<xsd:complexContent>
			<xsd:extension base="DataSetExt">
				<xsd:sequence>
					<xsd:element name="static_data" type="StaticData"
						minOccurs="1" maxOccurs="1" />
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="StaticData">
		<xsd:complexContent>
			<xsd:extension base="DataSetSpec">
				<xsd:sequence>
					<xsd:element name="static_rows" type="StaticRecords"
						minOccurs="1" maxOccurs="1" />
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="StaticRecords">
		<xsd:sequence>
			<xsd:element name="row" type="RowDef" minOccurs="1"
				maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="RowDef">
		<xsd:sequence>
			<xsd:element name="cell" type="RowCell" minOccurs="1"
				maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>

	<!-- CSV DataSet -->

	<xsd:complexType name="CsvDataSetDescr">
		<xsd:complexContent>
			<xsd:extension base="DataSetExt">
				<xsd:sequence>
					<xsd:element name="csv_data" type="CsvData" minOccurs="1"
						maxOccurs="1" />
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="CsvData">
		<xsd:complexContent>
			<xsd:extension base="DataSetSpec">
				<xsd:attribute name="file_name" type="xsd:string" use="required">
					<xsd:annotation>
						<xsd:documentation>The file name is relative to the
							project folder
						</xsd:documentation>
					</xsd:annotation>
				</xsd:attribute>
				<xsd:attribute name="delim" type="xsd:string" default="," />
				<xsd:attribute name="quote_char" type="xsd:string" default="&quot;" />
				<xsd:attribute name="escape_char" type="xsd:string" default="\" />
				<xsd:attribute name="col_first_row" type="xsd:boolean"
					default="true" />
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<!-- SQL DataSet -->
	<xsd:complexType name="SqlDataSetDescr">
		<xsd:complexContent>
			<xsd:extension base="DataSetExt">
				<xsd:sequence>
					<xsd:element name="sql_data" type="SqlData" minOccurs="1"
						maxOccurs="1" />
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="SqlData">
		<xsd:complexContent>
			<xsd:extension base="DataSetSpec">
				<xsd:sequence>
					<xsd:element name="sql" minOccurs="1" maxOccurs="1"
						type="SqlDef" />
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="SqlDef">
		<xsd:sequence>
			<xsd:element name="descr" type="xsd:string" minOccurs="0"
				maxOccurs="1" />
			<xsd:element name="sql_text" type="xsd:string" minOccurs="1"
				maxOccurs="1" />
			<xsd:element name="sql_params" type="SqlParameters"
				minOccurs="0" maxOccurs="1" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="SqlParameters">
		<xsd:sequence>
			<xsd:element name="param" type="SqlParameter" minOccurs="1"
				maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="SqlParameter">
		<xsd:complexContent>
			<xsd:extension base="OrderedList">
				<xsd:attribute name="req_param" type="xsd:IDREF" />
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<!-- XML DataSet Start -->
	<xsd:complexType name="XmlDataSetDescr">
		<xsd:complexContent>
			<xsd:extension base="DataSetExt">
				<xsd:sequence>
					<xsd:element name="xml_data" type="XmlData" minOccurs="1"
						maxOccurs="1" />
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="XmlData">
		<xsd:complexContent>
			<xsd:extension base="DataSetSpec">
				<!-- TODO -->
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

</xsd:schema>

=== pvf70/OsBiToolsWs/OsBiWsDsShared/src/test/resources/com/osbitools/ws/shared/demo/config/ds/test/static_test_calc_date1.xml
<?xml version="1.0" encoding="UTF-8"?>
<ds xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://www.osbitools.com/xsd/ds.xsd"  
	ver_max="1" ver_min="0">
		
    <ex_columns>
        <auto_inc>
            <column name="COL2" start_from="9" inc_by="2" />
            <column name="COL3" start_from="1995"/>
        </auto_inc>
        
        <calc>
            <column java_type="java.lang.Long" name="COL4">
            	(new java.util.Date(@{COL1} + "/" + @{COL2} + 
            								"/" + @{COL3})).getTime()
            </column>
            <column java_type="java.lang.String" name="COL5">
            	new java.text.SimpleDateFormat("M/d/y").format(
            		new java.util.Date(@{COL1} + "/" + @{COL2} + "/" + @{COL3}))
            </column>
        </calc>
    </ex_columns>
    
	<static_data>
	    
		<columns>
			<column name="COL1" java_type="java.lang.Integer" on_error="" />
		</columns>

		<static_rows>
			<row>
				<cell name="COL1" value="1" />
			</row>
			<row>
				<cell name="COL1" value="2" />
			</row>
			<row>
				<cell name="COL1" value="3" />
			</row>
			<row>
				<cell name="COL1" value="4" />
			</row>
			<row>
				<cell name="COL1" value="5" />
			</row>
			<row>
				<cell name="COL1" value="6" />
			</row>
			<row>
				<cell name="COL1" value="7" />
			</row>
			<row>
				<cell name="COL1" value="8" />
			</row>
			<row>
				<cell name="COL1" value="9" />
			</row>
			<row>
				<cell name="COL1" value="10" />
			</row>
			<row>
				<cell name="COL1" value="11" />
			</row>
			<row>
				<cell name="COL1" value="12" />
			</row>
		</static_rows>
	</static_data>
</ds>

=== pvf70/OsBiToolsWs/OsBiWsDsShared/src/test/resources/com/osbitools/ws/shared/demo/config/ds/test/static_test_lmap_auto_inc.xml
<?xml version="1.0" encoding="UTF-8"?>
<ds xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://www.osbitools.com/xsd/ds.xsd"
	ver_max="1" ver_min="0">

	<lang_map>
		<column name="COL1" />
	</lang_map>

	<ex_columns>
		<auto_inc>
			<column name="COL2" inc_by="5" start_from="-5" />
			<column name="COL3" />
		</auto_inc>
	</ex_columns>

	<static_data>

		<columns>
			<column name="COL1" java_type="java.lang.String" on_error="" />
		</columns>

		<static_rows>
			<row>
				<cell name="COL1" value="LL_USERNAME" />
			</row>

			<row>
				<cell name="COL1" value="LL_PASSWORD" />
			</row>
		</static_rows>
	</static_data>
</ds>

=== pvf70/OsBiToolsWs/OsBiWsDsShared/src/test/resources/com/osbitools/ws/shared/demo/config/ds/ds.xml
<?xml version="1.0" encoding="UTF-8"?>
<ds xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://www.osbitools.com/xsd/ds.xsd"
	descr="Test DataSet" enabled="true" ver_max="1" ver_min="0">

	<lang_map>
		<column name="COL1" />
		<column name="COL2" />
	</lang_map>

	<ex_columns>
		<auto_inc>
			<column name="A11" />
			<column name="B22" />
		</auto_inc>

		<calc>
			<column java_type="java.lang.Integer" name="CALC1">A + B</column>
			<column java_type="java.lang.String" name="CALC2">C + D</column>
		</calc>
	</ex_columns>

	<sort_by_grp>
		<sort_by idx="1" column="COL1" sequence="asc" unique="false" />
		<sort_by idx="2" column="COL2" sequence="desc" unique="false" />
	</sort_by_grp>

	<filter><![CDATA[A < B]]></filter>

	<group_data>
		<columns>
			<column name="COL1" java_type="java.lang.String" on_error="" />
			<column name="COL2" java_type="java.lang.String" on_error="" />
			<column name="A11" java_type="java.lang.Integer" on_error="" />
			<column name="B22" java_type="java.lang.Integer" on_error="" />
			<column name="CALC1" java_type="java.lang.Integer" on_error="" />
			<column name="CALC2" java_type="java.lang.String" on_error="" />
		</columns>
		<ds_list>
		  <!-- Group Item #1 -->
			<group_ds>
				<group_data>
					<ds_list>
					  <!-- Combine all 4 dataset types -->
					  
					  <!-- Group -->
						<group_ds>
							<sort_by_grp>
								<sort_by idx="1" column="COL1" />
							</sort_by_grp>
							<group_data>
								<ds_list>
									<static_ds>
										<static_data>
											<columns>
												<column name="COL1" java_type="java.lang.String"
													on_error="ERROR GRP 1-1-1 !!!" />
												<column name="COL2" java_type="java.lang.String"
													on_error="ERROR GRP 1-1-1 !!!" />
											</columns>
											<static_rows>
												<row>
													<cell name="COL1" value="UUu" />
													<cell name="COL2" value="ЦцЦ" />
												</row>
												<row>
													<cell name="COL1" value="dDd" />
													<cell name="COL2" value="ЗЗз" />
												</row>
											</static_rows>
										</static_data>
									</static_ds>

									<static_ds>
										<static_data>
											<columns>
												<column name="COL1" java_type="java.lang.String"
													on_error="ERROR GRP 1-1-2 !!!" />
												<column name="COL2" java_type="java.lang.String"
													on_error="ERROR GRP 1-1-2 !!!" />
											</columns>
											<static_rows>
												<row>
													<cell name="COL1" value="uuU" />
													<cell name="COL2" value="Ццц" />
												</row>
												<row>
													<cell name="COL1" value="Ddd" />
													<cell name="COL2" value="ЗЗз" />
												</row>
											</static_rows>
										</static_data>
									</static_ds>
								</ds_list>
							</group_data>
						</group_ds>
						
						<!-- Static -->
						<static_ds>
							<static_data>
								<columns>
									<column name="COL1" java_type="java.lang.String"
										                        on_error="ERROR GRP 1-2-1 !!!" />
									<column name="COL2" java_type="java.lang.String"
										                        on_error="ERROR GRP 1-2-1 !!!" />
								</columns>
								<static_rows>
									<row>
										<cell name="COL1" value="uUu" />
										<cell name="COL2" value="цЦц" />
									</row>
									<row>
										<cell name="COL1" value="Ddd" />
										<cell name="COL2" value="ЗзЗ" />
									</row>
								</static_rows>
							</static_data>
						</static_ds>

						<!-- Csv -->
						<csv_ds>
						  <csv_data file_name="filter_complex_no_header.csv" col_first_row="false">
				        <columns>
				            <column java_type="java.lang.String" name="COL1" on_error="" />
				            <column java_type="java.lang.String" name="COL2" on_error="" />
				        </columns>
              </csv_data>
						</csv_ds>
						
						<!-- Sql -->
						<sql_ds>
						  <sql_data>
                <sql>
                  <descr>Simple Select</descr>
                  <sql_text>SELECT * FROM TEST_DATA</sql_text>
                </sql>
              </sql_data>
						</sql_ds>
					</ds_list>
				</group_data>
			</group_ds>
			
			<!-- Group Item #2 -->
			<static_ds>
				<lang_map>
					<column name="COL1" />
					<column name="COL2" />
				</lang_map>

				<static_data>
					<columns>
						<column name="COL1" java_type="java.lang.String" 
						                                on_error="ERROR GRP 2 !!!" />
						<column name="COL2" java_type="java.lang.String" 
						                                      on_error="ERROR GRP 2 !!!" />
					</columns>
					<static_rows>
						<row>
							<cell name="COL1" value="bBb" />
							<cell name="COL2" value="УуУ" />
						</row>
						<row>
							<cell name="COL1" value="AaA" />
							<cell name="COL2" value="пПп" />
						</row>
					</static_rows>
				</static_data>
			</static_ds>
		</ds_list>
	</group_data>
</ds>

=== pvf70/OsBiToolsWs/OsBiWsDsShared/src/test/resources/com/osbitools/ws/shared/demo/config/ds/test/static_test_str1.xml
<?xml version="1.0" encoding="UTF-8"?>
<ds xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://www.osbitools.com/xsd/ds.xsd" ver_max="1" ver_min="0">
	
    <sort_by_grp>
		<sort_by idx="1" column="COL1" str_sort="collator" />
	</sort_by_grp>
	
	<static_data>
		<columns>
			<column name="COL1" java_type="java.lang.String" on_error="" />
			<column name="COL2" java_type="java.lang.String" on_error="" />
			<column name="COL3" java_type="java.lang.String" on_error="" />
		</columns>

		<static_rows>
			<row>
				<cell name="COL1" value="A1" />
				<cell name="COL2" value="B1" />
				<cell name="COL3" value="C1" />

			</row>

			<row>
				<cell name="COL1" value="a2" />
				<cell name="COL2" value="b2" />
				<cell name="COL3" value="c2" />
			</row>

			<row>
				<cell name="COL1" value="A2" />
				<cell name="COL2" value="B2" />
				<cell name="COL3" value="C2" />
			</row>

			<row>
				<cell name="COL1" value="a1" />
				<cell name="COL2" value="b1" />
				<cell name="COL3" value="c1" />
			</row>
		</static_rows>
	</static_data>
</ds>

=== pvf70/OsBiToolsWs/OsBiWsDsShared/src/test/resources/com/osbitools/ws/shared/demo/config/ds/test/csv_filter_params.xml
<?xml version="1.0" encoding="UTF-8"?>
<ds xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://www.osbitools.com/xsd/ds.xsd"  
	ver_max="1" ver_min="0">
    
    <sort_by_grp>
        <sort_by idx="1" column="CDATE" sequence="asc"/>
        <sort_by idx="2" column="CSTR" str_sort="natural"/>
    </sort_by_grp>
    
    <filter>${date_from}.before(@{CDATE}) &amp;&amp;
          @{CNUM} &gt; ${num_from} &amp;&amp;
          ${date_to}.after(@{CDATE}) &amp;&amp;
          @{CNUM} &lt; ${num_to}
    </filter>
    
    <req_params>
        <param java_type="java.util.Date" name="date_from"/>
        <param java_type="java.util.Date" name="date_to"/>
        <param java_type="java.lang.Double" name="num_from"/>
        <param java_type="java.lang.Double" name="num_to"/>
    </req_params>
    
    <csv_data file_name="filter_complex.csv">
        <columns>
            <column java_type="java.util.Date" name="CDATE" on_error="" />
            <column java_type="java.lang.Double" name="CNUM" on_error="" />
        </columns>
    </csv_data>
</ds>

=== pvf70/OsBiToolsWs/OsBiWsDsShared/src/test/resources/com/osbitools/ws/shared/demo/config/ds/test/csv_filter_complex.xml
<?xml version="1.0" encoding="UTF-8"?>
<ds xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://www.osbitools.com/xsd/ds.xsd"  
	ver_max="1" ver_min="0">

    <sort_by_grp>
        <sort_by idx="1" column="CDATE" sequence="asc"/>
        <sort_by idx="2" column="CNUM" sequence="desc" str_sort="natural"/>
    </sort_by_grp>
    
    <filter>(new java.util.Date("01/01/2007")).before(@{CDATE}) &amp;&amp;
          @{CNUM} &gt; 4d &amp;&amp;
          (new java.util.Date("12/31/2007")).after(@{CDATE}) &amp;&amp;
          @{CNUM} &lt; 6d</filter>
    
    <csv_data file_name="filter_complex.csv">
        <columns>
            <column java_type="java.util.Date" name="CDATE" on_error="" />
            <column java_type="java.lang.Double" name="CNUM" on_error="" />
        </columns>
    </csv_data>
</ds>

=== pvf70/OsBiToolsWs/OsBiWsDsShared/src/test/resources/com/osbitools/ws/shared/demo/config/ds/test/static_test_lmap_calc.xml
<?xml version="1.0" encoding="UTF-8"?>
<ds xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://www.osbitools.com/xsd/ds.xsd"  ver_max="1" ver_min="0">
	
    <lang_map>
		<column name="COL1" />
	</lang_map>
	
    <ex_columns>
        <auto_inc>
            <column name="COL2" inc_by="5" start_from="-5"/>
            <column name="COL3"/>
        </auto_inc>
        
        <calc>
            <column java_type="java.lang.Integer" name="COL4">@{COL2} + 
                										@{COL3}</column>
            <column java_type="java.lang.Integer" name="COL5">@{COL2} + 
                	@{COL3} + @{COL2} * 2 + @{COL2}* @{COL3} + @{COL3} * 
                	@{COL3} </column>
            <column java_type="java.lang.Integer" name="COL6" 
                stop_on_error="false" error_value="-100">@{COL2}/@{COL3} </column>
            <column java_type="java.lang.Double" name="COL7">new Double(@{COL2})/new Double(@{COL3} + 1) </column>
            <column java_type="java.lang.String" name="COL8">@{COL1} + " " + 
                	@{COL1} + " " + @{COL2}*@{COL2}</column>
        </calc>
    </ex_columns>
    
	<static_data>
	    
		<columns>
			<column name="COL1" java_type="java.lang.String" on_error="" />
		</columns>

		<static_rows>
			<row>
				<cell name="COL1" value="LL_USERNAME" />
			</row>

			<row>
				<cell name="COL1" value="LL_PASSWORD" />
			</row>
			
			<row>
				<cell name="COL1" value="LL_LETS_GO" />
			</row>
		</static_rows>
	</static_data>
</ds>

=== pvf70/OsBiToolsWs/OsBiWsDsShared/src/test/resources/com/osbitools/ws/shared/demo/config/ds/test/csv_filter_complex_no_header.xml
<?xml version="1.0" encoding="UTF-8"?>
<ds xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://www.osbitools.com/xsd/ds.xsd"  
	ver_max="1" ver_min="0">

    <sort_by_grp>
        <sort_by idx="1" column="COL4" sequence="asc"/>
        <sort_by idx="2" column="COL3" str_sort="natural"/>
    </sort_by_grp>
    
    <filter>(new java.util.Date("01/01/2007")).before(@{COL4}) &amp;&amp;
          @{COL3} &gt; 4d &amp;&amp;
          (new java.util.Date("12/31/2007")).after(@{COL4}) &amp;&amp;
          @{COL3} &lt; 6d</filter>
    
    <csv_data file_name="filter_complex_no_header.csv" col_first_row="false">
        <columns>
            <column java_type="java.util.Date" name="COL4" on_error="" />
            <column java_type="java.lang.Double" name="COL3" on_error="" />
        </columns>
    </csv_data>
</ds>
